version: '3.9'

networks:
  app:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.production
    ports:
      - '3000:3000'
    env_file: ./.env.production
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - app
